devrnt/react-use-intercom

README.md
example/app.tsx
example/modules/common/button.tsx
example/modules/common/index.ts
example/modules/common/page.tsx
example/modules/common/style.tsx
example/modules/provider/provider.tsx
example/modules/useIntercom/useIntercom.tsx
example/package.json
src/context.tsx
src/contextTypes.ts
test/useIntercom.test.tsx

Update readme with `react-use-intercom` features.
* Add `example` playground. This is both used for e2e tests and playground. Maybe in the future these two should be seperated.
* Add `console.error` when `useIntercom` was called and no `IntercomProvider` was supplied.

feature: add docs and example playground

---

example/app.tsx
example/modules/common/style.tsx
example/modules/index.ts
example/modules/useIntercom/index.ts
example/modules/useIntercom/useIntercom.tsx
example/modules/useIntercom/useIntercomTour.tsx

Add `useIntercom` example playground to start a tour
* Add new page in example playground to showcase the `startTour` function from `useIntercom`

docs: add start tour in example playground

---

README.md
example/modules/useIntercom/useIntercomTour.tsx
src/provider.tsx
src/utils.tsx

Passing "not allowed" props to `IntercomProvider` will cause a `console.error`.
Closes #11

feature: improve error logging in intercom provider

---

README.md
cypress/integration/mappers.ts
cypress/integration/visitorId.ts
example/modules/useIntercom/useIntercom.tsx
src/mappers.ts
src/types.ts

Resolves issue where custom attributes were not passed to Intercom.
* Add "super-seeded" boot in playground 
* Add mapping tests, camel cased attributes should correctly be passed to Intercom. E.g. `appId` to `app_id`, `verticalPadding` to `vertical_padding`...
* Update `IntercomProps` to receive a `customAttributes` prop. This is an object with all the raw custom attribute key-value entries.
Fixes #16, #17

fix: correctly pass custom attributes

---

README.md

Add extra remarks about `IntercomProvider` and `useIntercom`. Add "troubleshoot" section in readme.
* `IntercomProvider` should be placed  as high in the tree as possible.
* `useIntercom` can't be called in the same component where `IntercomProvider` was initialized.
* Add "Troubleshoot" section in readme. This will keep track of some common occured "problems/issues"
Closes #13

docs: add extra remarks and troubleshoot section

---

config/test.ts
src/context.tsx
src/provider.tsx
tsconfig.json

Disable `allowSyntheticDefaultImports` in `tsconfig` so we have to use namespace import
* Reduce bundlesize because of React namespace imports: https://twitter.com/sebmarkbage/status/1250284377138802689

refactor: use react namespace imports

---

src/provider.tsx

Using `useState` in `IntercomProvider` causes unnecessary rerenders. This is avoided by making use of `useRef`.
* Drop the `isBooted` dependency in the `useCallbacks`'s. 
As of now the `IntercomProvider` causes no rerenders on `boot`, `update` and so on...

feature: avoid rerenders

---

src/api.ts
src/intercom.ts
src/provider.tsx

* Use custom logger instead of logging directly with `console.log`
* Add extra logging when `shouldInitialize` is set to `false` in `IntercomProvider`. Log a warning to let the developer know that the `IntercomProvider` was explicitly not initialized.
* Rename `intercom.tsx` to `api.tsx` and use `default` export/import

refactor: improve logging and cleanup

---

src/mappers.ts
src/types.ts

This PR allows custom attributes to be passed to companies.
In general, I think this library would be better without the mapping logic, as the serialization to & from snakeCase/camelCase is an unnecessary complication.

fix: allows customAttributes to be passed to company records

---

src/api.ts
src/provider.tsx
src/utils.tsx

This PR checks for `typeof window === 'undefined'` to safeguard against any usage of window if it is not present. 
This module will now work in SSRd environments such as Next.js.
Thanks for the meticulously typed package 👍

fix: safeguards against SSR environments without access to window

---

src/logger.ts

Make use of [babel-plugin-dev-expression]( https://github.com/4Catalyzer/babel-plugin-dev-expression#readme) to only show logs in development mode.
This result in a production bundle without the (development) logs. As well as a bundlesize reduction of 0.28kB

chore: only show logs in development mode

---

src/initialize.ts
test/setup.ts

If `IntercomProvider` is placed deeper inside the component tree, it is very likely that window load event was already fired before initialize() had a chance to add the event listener. Check for document.readyState to attach the intercom script even if the page was already loaded.

Improve initialize()

---

README.md
src/provider.tsx

This allows react-use-intercom to "hook" onto an existing instance of Intercom, e.g., loaded in by another platform such as [Segment](https://segment.com/).
- react-use-intercom should control an existing Intercom instance
- listeners should not be re-attached when the provider re-renders

Support attaching to an existing Intercom instance

---

README.md
playground/modules/useIntercom/useIntercom.tsx
src/provider.tsx
src/types.ts

The Intercom Javascript API now supports opening an article in the Messenger widget (see: https://developers.intercom.com/installing-intercom/docs/intercom-javascript#intercomshowarticle-articleid)
This PR exposes that API through the useIntercom hook.

expose intercom JS API 'showArticle' function through useIntercom

---

src/provider.tsx

Fix TypeScript react type. This would result in TypeScript issues when using with the React 18 types, see https://twitter.com/reactjs/status/1512453969490108418
https://github.com/devrnt/react-use-wizard/pull/115

Add PropsWithChildren React type

---

README.md
src/provider.tsx
src/types.ts

Hi ! I re-open [this PR ](https://github.com/devrnt/react-use-intercom/pull/509) because it seems like my previous explanations were not clear enough.
The problem does not come from this lib side, but from the Intercom side. Let me be more precise: when you register a callback with Intercom('onShow') and Intercom('onHide'), there is absolutely no way to remove it . I mean, this is not implemented in the Intercom object.
So you're correct when you say it's perfectly possible to keep track of the opening status in a local state, attaching listeners in a useEffect hook. The problem is that as you can't remove the added listeners, they will continue to exist even after the unmounting of your component. It's not a big memory leak, but it is one, and it is not wanted for clean stuff.
The only …

feat: add isOpen flag to useIntercom() (re-open)

---

src/provider.tsx
src/types.ts

The attribute to do a "page view" update (without user attribute changes) is `last_request_at`, rather than `last_requested_at`. This translates to the default attribute in the Intercom UI "Last Seen" ([source](https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects#mapping-of-javascript-attributes-to-intercom-dashboard-and-api))
Also, the attribute takes seconds rather than milliseconds.
Here's the documentation which talks about doing page view updates: https://www.intercom.com/help/en/articles/170-integrate-intercom-in-a-single-page-app
-----
With the current version of this package, user objects in Intercom have the following invalid attribute:

Change last_requested_at to last_request_at

---

.changeset/tame-chairs-build.md
README.md
apps/playground/src/modules/useIntercom/useIntercom.tsx
packages/react-use-intercom/README.md
packages/react-use-intercom/src/provider.tsx
packages/react-use-intercom/src/types.ts

Added [showSpace](https://developers.intercom.com/installing-intercom/docs/intercom-javascript#intercomshowspace-spacename) method to open the Messenger with the specified space. The functionality of spaces is pretty fresh in the Intercom API, so I'm not sure if this is the best way to do it. I'm happy to change it if there's a better way.

feat: add showSpace method

---

.changeset/lazy-countries-obey.md
README.md
packages/react-use-intercom/README.md
packages/react-use-intercom/src/provider.tsx
packages/react-use-intercom/src/types.ts

This PR exposes the IntercomAPI startChecklist method so it can be used by the clients of the useIntercom hook.

Expose Start Checklist

---

.changeset/smart-pots-cry.md
README.md
packages/react-use-intercom/README.md
packages/react-use-intercom/src/provider.tsx
packages/react-use-intercom/src/types.ts

Exposes showTicket and showConversation methods in useIntercom hook
Closes https://github.com/devrnt/react-use-intercom/issues/670

expose showTicket and showConversation

---

.changeset/khaki-sloths-heal.md
packages/react-use-intercom/src/mappers.ts
packages/react-use-intercom/src/types.ts

There's currently no way to pass the `z_index` property to Intercom. This just adds it into the mapping alongside horizontalPadding and similar, to be used like this:
```
<IntercomProvider
autoBootProps={{zIndex: 1000}}
/>
```

Add support for `zIndex` property 

---

.changeset/moody-garlics-begin.md
packages/react-use-intercom/src/mappers.ts
packages/react-use-intercom/src/types.ts

Add intercom user jwt
